name: Branch Workflow with Manual Approvals

on:
  push:
    branches:
      - dev_mayank      # Auto trigger on push to dev_mayank
  workflow_dispatch:    # Allows manual trigger from GitHub Actions UI

jobs:
  approval-and-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository code
        uses: actions/checkout@v2

      # Step 2: Auto-trigger when code is pushed to dev_mayank
      - name: Auto Trigger for dev_mayank
        if: github.ref == 'refs/heads/dev_mayank'
        run: echo "Changes pushed to dev_mayank. Please trigger workflow_dispatch to merge to DEV."

      # Step 3: Wait for Manual Approval (Handled by workflow_dispatch)
      - name: Wait for Manual Approval to Merge to DEV
        if: github.event_name == 'workflow_dispatch'
        run: echo "Manual approval received, proceeding with merge to DEV."

      # Step 4: Merge changes to DEV branch after approval
      - name: Merge changes to DEV branch
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout DEV
          git merge --no-ff dev_mayank
          git push origin DEV

      # Step 5: Create Pull Request from DEV to UAT
      - name: Create Pull Request from DEV to UAT
        run: |
          gh pr create --base UAT --head DEV --title "Merge from DEV to UAT" --body "Automated PR after DEV approval."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Wait for Manual Approval for UAT (Handled by workflow_dispatch)
      - name: Wait for Manual Approval to Merge to UAT
        if: github.event_name == 'workflow_dispatch'
        run: echo "Manual approval received, proceeding with merge to UAT."

      # Step 7: Merge changes to UAT branch after approval
      - name: Merge changes to UAT branch
        if: github.event_name == 'workflow_dispatch'
        run: |
          git checkout UAT
          git merge --no-ff DEV
          git push origin UAT

      # Step 8: Create Pull Request from UAT to main
      - name: Create Pull Request from UAT to main
        run: |
          gh pr create --base main --head UAT --title "Merge from UAT to main" --body "Automated PR after UAT approval."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 9: Wait for Manual Approval for Main (Handled by workflow_dispatch)
      - name: Wait for Manual Approval to Merge to Main
        if: github.event_name == 'workflow_dispatch'
        run: echo "Manual approval received, proceeding with merge to main."

      # Step 10: Merge changes to main branch after approval
      - name: Merge changes to main branch
        if: github.event_name == 'workflow_dispatch'
        run: |
          git checkout main
          git merge --no-ff UAT
          git push origin main
