name: Branch Workflow with Manual Approvals

on:
  push:
    branches:
      - dev_mayank      # Auto trigger on push to dev_mayank
  pull_request:
    branches:
      - dev             # Trigger on PR to dev
      - UAT             # Trigger on PR to UAT
      - main            # Trigger on PR to main

jobs:
  approval-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      # Step 1: Auto-trigger when code is pushed to dev_mayank
      - name: Auto Trigger for dev_mayank
        if: github.ref == 'refs/heads/dev_mayank'
        run: echo "Changes pushed to dev_mayank, waiting for manual approval to merge to dev."

      # Step 2: Manual approval for merging to dev
      - name: Wait for Manual Approval to Merge to Dev
        if: github.ref == 'refs/heads/dev_mayank'
        uses: peter-evans/approval-action@v2
        with:
          approval-type: 'manual'
          approval-message: 'Please approve merging changes from dev_mayank to dev branch.'

      - name: Merge changes to dev branch
        if: github.ref == 'refs/heads/dev_mayank'
        run: |
          git checkout dev
          git merge --no-ff ${{ github.head_ref }}
          git push origin dev

      # Step 3: Manual approval for merging to UAT
      - name: Wait for Manual Approval to Merge to UAT
        if: github.event.pull_request.base.ref == 'UAT'
        uses: peter-evans/approval-action@v2
        with:
          approval-type: 'manual'
          approval-message: 'Please approve merging to the UAT branch.'

      - name: Merge changes to UAT branch
        if: github.event.pull_request.base.ref == 'UAT'
        run: |
          git checkout UAT
          git merge --no-ff ${{ github.head_ref }}
          git push origin UAT

      # Step 4: Manual approval for merging to main branch
      - name: Wait for Manual Approval to Merge to Main
        if: github.event.pull_request.base.ref == 'main'
        uses: peter-evans/approval-action@v2
        with:
          approval-type: 'manual'
          approval-message: 'Please approve merging to the main branch.'

      - name: Merge changes to main branch
        if: github.event.pull_request.base.ref == 'main'
        run: |
          git checkout main
          git merge --no-ff ${{ github.head_ref }}
          git push origin main
